[package]
name = "srch"
version = "0.0.3"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
regex =  "1.1.1"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0"
